docker:
  publish: false
  builds:
    - dockerfile: Dockerfile
      docker_repo: resin/open-balena-db
      path: .

    - dockerfile: Dockerfile
      docker_repo: balena/open-balena-db
      path: .
